In [2]:
from IPython.display import Image
Image(url='http://datascience.uci.edu/wp-content/uploads/sites/2/2014/09/data_science_logo_with_image1.png')

## Preliminaries

1. We assume that you've already installed the [Anaconda Python Distribution](https://store.continuum.io/cshop/anaconda/)
1. Download the course files at http://bit.ly/uci_python_2015 >> "Download Zip" (toward the bottom right)
1. Unzip the files onto your hard drive somewhere where you can access them easily.  You'll need to find them several times throughout the day.

### Schedule for Today

|Start Time | Session |
|-----------|---------|
|8:30am     | Check In|
|9:00am     | **The IPython Notebook and Pandas** |
|10:30am    | Coffee & Bagels|
|10:45am    | **Linear Regression and Predictive Modeling** |
|12:30pm    | Lunch|
|1:00pm     | **Out of Sample Prediction** |
|2:45pm     | Afternoon break|
|3:00pm     | **Logistic Regression** |

## Predictive Modeling with Python - _IPython Notebooks and Viewing Data in Python_
#### Author: Kevin Bache

## Outline
1. IPython
2. IPython Notebooks
3. Numpy
4. Pandas

## Python and IPython
* `python` is a programming language and also the name of the program that runs scripts written in that language.
* If you're running scripts from the command line you can use either `ipython` with something like `ipython my_script.py` or `python` with something like `python my_script.py`
* If you're using the command line interpreter interactively to load and explore data, try out a new package, etc. always use `ipython` over `python`.  This is because `ipython` has a bunch of features that are just plain great:


##### TODO: remove all exercise timings.  You won't stick to them anyway.  Have them as separate notes maybe


##### TODO: before the class:
1. Install anaconda.  It doesn't matter if you already have python or ipython or use the ipython notebook every day.  Install anaconda.  On osx, do check 'modify path' to let it make itself your primary python distribution.
1. If you already have anaconda installed, run:
    1. conda update conda
    1. conda update anaconda
    1. conda update --all
1. Give them an ipython notebook with a bunch of import tests in it.  They should all pass.
    1. import numpy; print numpy.__version__
    1. import scipy; print scipy.__version__
    1. import pandas; print pandas.__version__
    1. import sklearn; 'scikit-learn is version %s and should be 0.16.1' % sklearn.__version__ 

##### TODO: how to start the class:
1. Opening a terminal
1. `conda` package manager.  what is it?  what does it do?  what does it replace?
1. Ensure that everything is up to date
1. Run `ipython notebook`
1. Navigate to where you stored the course folder in the notebook's file explorer
1. Look in the solutions folder.  Open one of the solutions files.  There are the solutions.
1. Go back and open session 0.  Now you have a copy of the notes
1. (Save ipython terminal for the very end -- maybe)

* `python` is a programming language and also the name of the program that runs scripts written in that language.
* If you're running scripts from the command line you can use either `ipython` with something like `ipython my_script.py` or `python` with something like `python my_script.py`
    * If you're using the command line interpreter interactively to load and explore data, try out a new package, etc. always use `ipython` over `python`.  This is because `ipython` has a bunch of features that are just plain great:


##### TODO: 
1. can't do x = !ls; print x because 1) you can't have anything on the line after !ls and 2) ls doesn't work on windows.
1. include an exercise which is all about getting np.dot() to work with various inputs.  matrix, vector; matrix, matrix; matrix, 1d-matrix; etc.  have them identify the error messages they'll see when that's the problem.
1. include an exercise whihc is all about getting np.hstack to work.  it needs one argument -- a list of arrays -- not one argument per array
1. similarly, include an exercise which is all about getting np.ones((size1, size2)) to work
1. include an exercise showing that you can use pandas dataframes just like you can use 2d numpy arrays.  what happens when you put a 1d vector into a dataframe and then try to use e.g. np.dot()
1. include an exercise that's all about how to find help for each section (ipython notebook, numpy, pandas, etc).
    1. i.e.: first google it, then look in the help files for the package, then check stack overflow

### IPython Goodies
First run `import numpy` so the code below works.  

|Run this                     |For This Goodie   | Notes |
|-----------------------------|------------------|------|
|`numpy.ar` (then press tab)        | **Tab completion!**  | Tab completion is a great way to learn what methods a python object has available on it |
|`?numpy.arange`  | Easy access to **help!**    |This brings up a help screen, press 'q' to quit it when you're done |
|`x = !ls` and on the next line `print x`   | Easy access to **shell commands!** |  This stores the output of `ls` in a python list called x.  Now you can iterate over that list, filter it, whatever you'd like.  All without having to access the shell directly.  Very convenient! |

### <span style="color:red">IPython vs. Python Exercise: 8 Minutes</span>
1. Partner up with someone next to you.  Then, on one of your computers:
  1. Start a terminal and cd to the directory where you stored the course files
  1. Start the IPython shell by typing `ipython`.  In the `ipython` shell:
    1. Type `import numpy`
    1. Try the commands in the table above.  Describe to your partner what each command is doing.
  1. Open another terminal (leave the first one running).  Start the Python shell by typing `python`.  In the `python` shell:
    1. Type `import numpy`
    1. Try the commands in the table above.  Do they work?
    1. Close this `python` terminal
  1. Now, back in your original IPython terminal.
    1. Write a small program to print out the names of all IPython notebook files in the course directory.  
       **Hint**: IPython notebook files end with ".ipynb"
    1. Keep a copy of this program somewhere accessible.  You'll use it later.
     
That's IPython's interactive shell.  However, IPython also offers a second, even more powerful, environment called the IPython Notebook.

## IPython Notebook
* IPython notebook is an interactive front-end to ipython which lets you combine snippets of python code with explanations, images, videos, whatever.  
* It's also really convenient for conveying experimental results.
* http://nbviewer.ipython.org

### <span style="color:red">IPython Notebook Exercise #1: 3 Minutes</span>
1. Start a terminal window and cd to the directory where you stored the course files
1. Start the IPython Notebook server with the command `ipython notebook`.  The IPython notebook server runs your python code behind the scenes and renders the output into the notebook
1. Create a new notebook by clicking New (top right) >> Python 2 Notebook

### Notebook Concepts
* **Cells** -- That grey box is called a cell.  An IPython notebook is nothing but a series of cells.  
* **Selecting** -- You can tell if you have a cell selected because it will have a thin, black box around it.
* **Running a Cell** -- Running a cell displays its output.  You can run a cell by pressing **`shift + enter`** while it's selected (or click the play button toward the top of the screen). 
* **Modes** -- There are two different ways of having a cell selected:
  * **Command Mode** -- Lets you delete a cell and change its type (more on this in a second).
  * **Edit Mode** -- Lets you change the contents of a cell.

### Aside: Keyboard Shortcuts That I Use A Lot
* (When describing keyboard shortcuts, `+` means 'press at the same time', `,` means 'press after'
* **`Enter`** -- Run this cell and make a new one after it
* **`Esc`** -- Stop editing this cell
* **`Option + Enter`** -- Run this cell and make a new cell after it (Note: this is OSX specific.  Check help >> keyboard shortcuts to find your operating system's version)
* **`Shift + Enter`** -- Run this cell and don't make a new one after it
* **`Up Arrow`** and **`Down Arrow`**  -- Navigate between cells (must be in command mode)
* **`Esc, m, Enter`** -- Convert the current cell to markdown and start editing it again
* **`Esc, y, Enter`** -- Convert the current cell to a code cell and start editing it again
* **`Esc, d, d`** -- Delete the current cell
* **`Esc, a`** -- Create a new cell above the current one
* **`Esc, b`** -- Create a new cell below the current one
* **`Command + /`** -- Toggle comments in Python code (OSX)
* **`Ctrl + /`** -- Toggle comments in Python code (Linux / Windows)

### <span style="color:red">IPython Notebook Exercise #2: 8 Minutes</span>
1. Click Help >> User Interface Tour and take the tour
1. Click Help >> Keyboard Shortcuts.  Mice are for suckers.
1. Recreate the program you wrote earlier in the IPython terminal to print out the name of each IPython notebook in the current directory.

### More Notebook Concepts
* **Cell Types** -- There are 3 types of cells: python, markdown, and raw.
  * **Python Cells** -- Contain python code. Running a python cell displays its output. Press **`y`** in command mode convert any selected cell into a python cell. All cells start their lives as python cells.
  * **Markdown Cells** -- Contain formatted text, lists, links, etc. Press **`m`** in command mode to convert the selected cell into a markdown cell.
  * **Raw Cells** -- Useful for a few advanced corner cases.  We won't deal with these at all today.
  
### <span style="color:red">IPython Notebook Exercise #3: 12 Minutes</span>:
1. Partner up with someone next to you

  1. Create and render a markdown cell which contains bold text, a nested numbered list, a working link to UCI's website, an image, and some rendered LaTex. **Hint**: The following websites might be useful:
    1. Check out this [Markdown Cheat Sheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).  Markdown is a set of simple commands for formatting text to make it pretty.  It isn't specific to IPython Notebooks; it's used all over (for example, a lot of blogging platforms let you write your content in markdown because it's easy and HTML is a pain in the butt).
    1. Check out this [stackoverflow post](http://stackoverflow.com/questions/13208286/how-to-write-latex-in-ipython-notebook) about using LaTex in IPython Notebooks.

## Numpy
Numpy is the main package that you'll use for doing scientific computing in Python.  Numpy provides a multidimensional array datatype called `ndarray` which can do things like vector and matrix computations.

### Resources:
* [Official Numpy Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial)
* [Numpy, R, Matlab Cheat Sheet](http://mathesaurus.sourceforge.net/matlab-python-xref.pdf)
* [Another Numpy, R, Matlab Cheat Sheet](http://sebastianraschka.com/Articles/2014_matrix_cheatsheet_table.html)

In [3]:
# you don't have to rename numpy to np but it's customary to do so
import numpy as np

# you can create a 1-d array with a list of numbers
a = np.array([1, 4, 6])
print 'a:'
print a
print 'a.shape:', a.shape
print 

# you can create a 2-d array with a list of lists of numbers
b = np.array([[6, 7], [3, 1], [4, 0]])
print 'b:'
print b
print 'b.shape:', b.shape
print

a:
[1 4 6]
a.shape: (3,)

b:
[[6 7]
 [3 1]
 [4 0]]
b.shape: (3, 2)



In [9]:
# you can create an array of ones
print 'np.ones((3, 4)):'
print np.ones((3, 4))
print

# you can create an array of zeros
print 'np.zeros((2, 5)):'
print np.zeros((2, 5))
print

# you can create an array which of a range of numbers and reshape it
print 'np.arange(6):'
print np.arange(6)
print 
print 'np.arange(6).reshape(2, 3):'
print np.arange(6).reshape(2, 3)
print

# you can take the transpose of a matrix with .transpose or .T
print 'b and b.T:'
print b
print 
print b.T
print 
print b.transpose()
print 

np.ones((3, 4)):
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]

np.zeros((2, 5)):
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]

np.arange(6):
[0 1 2 3 4 5]

np.arange(6).reshape(2, 3):
[[0 1 2]
 [3 4 5]]

b and b.T:
[[6 7]
 [3 1]
 [4 0]]

[[6 3 4]
 [7 1 0]]

[[6 3 4]
 [7 1 0]]



In [13]:
# you can iterate over rows
i = 0
for this_row in b:
    print 'row', i, ': ', this_row
    i += 1 
print 
    
# you can access sections of an array with slices
print 'first two rows of the first column of b:'
print b[:2, 0]
print

row 0 :  [6 7]
row 1 :  [3 1]
row 2 :  [4 0]

first two rows of the first column of b:
[6 3]



In [16]:
# you can concatenate arrays in various ways:
print 'np.hstack([b, b]):'
print np.hstack([b, b])
print

print 'np.vstack([b, b]):'
print np.vstack([b, b])
print

np.hstack([b, b]):
[[6 7 6 7]
 [3 1 3 1]
 [4 0 4 0]]

np.vstack([b, b]):
[[6 7]
 [3 1]
 [4 0]
 [6 7]
 [3 1]
 [4 0]]



In [17]:
# note that you get an error if you pass in print 'np.hstack(b, b):'
print np.hstack(b, b)
print


TypeError: hstack() takes exactly 1 argument (2 given)

In [18]:
# you can perform matrix multiplication with np.dot()
c = np.dot(a, b)
print 'c = np.dot(a, b):'
print c
print

# you can perform element-wise multiplication with * 
d = b * b
print 'd = b * b:'
print d
print

c = np.dot(a, b):
[42 11]

d = b * b:
[[36 49]
 [ 9  1]
 [16  0]]



### Arrays and Matrices
In addition to arrays which can have any number of dimensions, Numpy also has a `matrix` data type which always has exactly 2.  **DO NOT USE `matrix`**.  

The original intention behind this data type was to make Numpy feel a bit more like Matlab, mainly by making the `*` operator perform matrix multiplication so you don't have to use `np.dot`.  But `matrix` isn't as well developed by the Numpy people as `array` is.  `matrix` is slower and using it will sometimes throw errors in other people's code because everyone expects you to use `array`.

In [19]:
# you can convert a 1-d array to a 2-d array with np.newaxis
print 'a:'
print a
print 'a.shape:', a.shape
print 
print 'a[np.newaxis] is a 2-d row vector:'
print a[np.newaxis]
print 'a[np.newaxis].shape:', a[np.newaxis].shape
print

print 'a[np.newaxis].T: is a 2-d column vector:'
print a[np.newaxis].T
print 'a[np.newaxis].T.shape:', a[np.newaxis].T.shape
print


a:
[1 4 6]
a.shape: (3,)

a[np.newaxis] is a 2-d row vector:
[[1 4 6]]
a[np.newaxis].shape: (1, 3)

a[np.newaxis].T: is a 2-d column vector:
[[1]
 [4]
 [6]]
a[np.newaxis].T.shape: (3, 1)



In [20]:
# numpy provides a ton of other functions for working with matrices
m = np.array([[1, 2],[3, 4]])
m_inverse = np.linalg.inv(m)
print 'inverse of [[1, 2],[3, 4]]:'
print m_inverse
print

inverse of [[1, 2],[3, 4]]:
[[-2.   1. ]
 [ 1.5 -0.5]]



In [27]:
# and for doing all kinds of sciency type stuff.  like generating random numbers:
np.random.seed(5678)
n = np.random.randn(3, 4)
print 'a matrix with random entries drawn from a Normal(0, 1) distribution:'
print n

a matrix with random entries drawn from a Normal(0, 1) distribution:
[[-0.70978938 -0.01719118  0.31941137 -2.26533107]
 [-1.37745366  1.94998073 -0.56381007 -0.84373759]
 [ 0.22453858 -0.39137772  0.60550347 -0.68615034]]


### <span style="color:red">Numpy Exercise -- 10 Minutes</span>
1. In the cell below, add a column of ones to the matrix `X_no_constant`.  This is a common task in linear regression and general linear modeling and something that you'll have to be able to do later today.  
1. Multiply your new matrix by the `betas` vector below to make a vector called `y`
1. You'll know you've got it when the cell prints '\*\*\*\*\*\* Tests passed! \*\*\*\*\*\*' at the bottom.

Specificically, given a matrix:

\begin{equation*}
\qquad
\mathbf{X_{NoConstant}} = 
\left( \begin{array}{ccc}
x_{1,1} & x_{1,2} & \dots & x_{1,D} \\
x_{2,1} & x_{2,2} & \dots & x_{2,D} \\
\vdots & \vdots & \ddots & \vdots \\
x_{i,1} & x_{i,2} & \dots & x_{i,D} \\
\vdots & \vdots & \ddots & \vdots \\
x_{N,1} & x_{N,2} & \dots & x_{N,D} \\
\end{array} \right)
\qquad
\end{equation*}

We want to convert it to:
\begin{equation*}
\qquad
\mathbf{X} = 
\left( \begin{array}{ccc}
1 & x_{1,1} & x_{1,2} & \dots & x_{1,D} \\
1 & x_{2,1} & x_{2,2} & \dots & x_{2,D} \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
1 & x_{i,1} & x_{i,2} & \dots & x_{i,D} \\
\vdots & \vdots & \ddots & \vdots \\
1 & x_{N,1} & x_{N,2} & \dots & x_{N,D} \\
\end{array} \right)
\qquad
\end{equation*}

So that if we have a vector of regression coefficients like this:

\begin{equation*}
\qquad
\beta = \left( \begin{array}{ccc}
\beta_0 \\
\beta_1 \\
\vdots \\
\beta_j \\
\vdots \\
\beta_D
\end{array} \right)
\end{equation*}

We can do this:

\begin{equation*}
\mathbf{y} \equiv \mathbf{X}^T \mathbf{\beta} 
\end{equation*}


In [52]:
np.random.seed(3333)
n_data = 10 # number of data points. i.e. N
n_dim = 5   # number of dimensions of each datapoint.  i.e. D

betas = np.random.randn(n_dim + 1)

X_no_constant = np.random.randn(n_data, n_dim)
# print 'X_no_constant:'
# print X_no_constant
# print 

ones = np.ones(n_data)
x = np.hstack([ones[np.newaxis].T, X_no_constant])
y = np.dot(x, betas)

# Tests:
y_expected = np.array([-0.41518357, -9.34696153, 5.08980544, 
                       -0.26983873, -1.47667864, 1.96580794, 
                       6.87009791, -2.07784135, -0.7726816, 
                       -2.74954984])
np.testing.assert_allclose(y, y_expected)
print '****** Tests passed! ******'

****** Tests passed! ******


## Pandas
Pandas is a python package which adds some useful data analysis features to numpy arrays.  Most importantly, it contains a `DataFrame` data type like the r `dataframe`: a set of named columns organized into something like a 2d array.  Pandas is great.

### Resources:
* [10 Minutes to Pandas](http://pandas.pydata.org/pandas-docs/dev/10min.html)
* [Pandas Data Structures Tutorial](http://pandas.pydata.org/pandas-docs/stable/dsintro.html)
* [Merge, Join, Concatenate Tutorial](http://pandas.pydata.org/pandas-docs/dev/merging.html)
* [Another Numpy/Pandas Tutorial](https://www.kaggle.com/c/titanic/details/getting-started-with-python-ii)

In [2]:
# like with numpy, you don't have to rename pandas to pd, but it's customary to do so
import pandas as pd

df = pd.DataFrame(data=b,  columns=['Weight', 'Height'])
print 'b:'
print b
print 
print 'DataFame version of b:'
print df
print

print np.dot(a, df)

NameError: name 'b' is not defined

In [3]:
# Pandas can save and load CSV files.  
# Python can do this too, but with Pandas, you get a DataFrame 
# at the end which understands things like column headings
baseball = pd.read_csv('data/baseball.dat.txt')

# A Dataframe's .head() method shows its first 5 rows
baseball.head()

Salary    AVG    OBP  Runs  Hits  Doubles  Triples  HR  RBI  Walks   SO  \
0    3300  0.272  0.302    69   153       21        4  31  104     22   80   
1    2600  0.269  0.335    58   111       17        2  18   66     39   69   
2    2500  0.249  0.337    54   115       15        1  17   73     63  116   
3    2475  0.260  0.292    59   128       22        7  12   50     23   64   
4    2313  0.273  0.346    87   169       28        5   8   58     70   53   

   SB  Errs  free agency eligibility  free agent in 1991/2  \
0   4     3                        1                     0   
1   0     3                        1                     1   
2   6     5                        1                     0   
3  21    21                        0                     0   
4   3     8                        0                     0   

   arbitration eligibility  arbitration in 1991/2            Name  
0                        0                      0    Andre Dawson  
1                        0                      0   Steve Buchele  
2                        0                      0     Kal Daniels  
3                        1                      0  Shawon Dunston  
4                        1                      0      Mark Grace

In [58]:
# you can see all the column names
print 'baseball.keys():'
print baseball.keys()
print

print 'baseball.Salary:'
print baseball.Salary
print 
print "baseball['Salary']:"
print baseball['Salary']

baseball.keys():
Index([u'Salary', u'AVG', u'OBP', u'Runs', u'Hits', u'Doubles', u'Triples', u'HR', u'RBI', u'Walks', u'SO', u'SB', u'Errs', u'free agency eligibility', u'free agent in 1991/2', u'arbitration eligibility', u'arbitration in 1991/2', u'Name'], dtype='object')

baseball.Salary:
0     3300
1     2600
2     2500
3     2475
4     2313
5     2175
6      600
7      460
8      240
9      200
10     177
11     140
12     117
13     115
14    2600
...
322    4300
323    3850
324    2387
325     950
326     675
327     600
328     287
329     230
330     215
331     183
332     170
333     160
334     142
335     140
336     109
Name: Salary, Length: 337, dtype: int64

baseball['Salary']:
0     3300
1     2600
2     2500
3     2475
4     2313
5     2175
6      600
7      460
8      240
9      200
10     177
11     140
12     117
13     115
14    2600
...
322    4300
323    3850
324    2387
325     950
326     675
327     600
328     287
329     230
330     215
331     183
332     1

In [59]:
baseball.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 337 entries, 0 to 336
Data columns (total 18 columns):
Salary                     337 non-null int64
AVG                        337 non-null float64
OBP                        337 non-null float64
Runs                       337 non-null int64
Hits                       337 non-null int64
Doubles                    337 non-null int64
Triples                    337 non-null int64
HR                         337 non-null int64
RBI                        337 non-null int64
Walks                      337 non-null int64
SO                         337 non-null int64
SB                         337 non-null int64
Errs                       337 non-null int64
free agency eligibility    337 non-null int64
free agent in 1991/2       337 non-null int64
arbitration eligibility    337 non-null int64
arbitration in 1991/2      337 non-null int64
Name                       337 non-null object
dtypes: float64(2), int64(15), object(1)
memory usage: 50.0+ K

In [62]:
baseball.describe()

Salary         AVG         OBP        Runs        Hits  \
count   337.000000  337.000000  337.000000  337.000000  337.000000   
mean   1248.528190    0.257825    0.323973   46.697329   92.833828   
std    1240.013309    0.039546    0.047132   29.020166   51.896322   
min     109.000000    0.063000    0.063000    0.000000    1.000000   
25%     230.000000    0.238000    0.297000   22.000000   51.000000   
50%     740.000000    0.260000    0.323000   41.000000   91.000000   
75%    2150.000000    0.281000    0.354000   69.000000  136.000000   
max    6100.000000    0.457000    0.486000  133.000000  216.000000   

          Doubles     Triples          HR         RBI       Walks          SO  \
count  337.000000  337.000000  337.000000  337.000000  337.000000  337.000000   
mean    16.673591    2.338279    9.097923   44.020772   35.017804   56.706231   
std     10.452001    2.543336    9.289934   29.559406   24.842474   33.828784   
min      0.000000    0.000000    0.000000    0.000000    0.000000    1.000000   
25%      9.000000    0.000000    2.000000   21.000000   15.000000   31.000000   
50%     15.000000    2.000000    6.000000   39.000000   30.000000   49.000000   
75%     23.000000    3.000000   15.000000   66.000000   49.000000   78.000000   
max     49.000000   15.000000   44.000000  133.000000  138.000000  175.000000   

               SB        Errs  free agency eligibility  free agent in 1991/2  \
count  337.000000  337.000000               337.000000            337.000000   
mean     8.246291    6.771513                 0.397626              0.115727   
std     11.664782    5.927490                 0.490135              0.320373   
min      0.000000    0.000000                 0.000000              0.000000   
25%      1.000000    3.000000                 0.000000              0.000000   
50%      4.000000    5.000000                 0.000000              0.000000   
75%     11.000000    9.000000                 1.000000              0.000000   
max     76.000000   31.000000                 1.000000              1.000000   

       arbitration eligibility  arbitration in 1991/2  
count               337.000000             337.000000  
mean                  0.192878               0.029674  
std                   0.395145               0.169938  
min                   0.000000               0.000000  
25%                   0.000000               0.000000  
50%                   0.000000               0.000000  
75%                   0.000000               0.000000  
max                   1.000000               1.000000

In [63]:
baseball

Salary    AVG    OBP  Runs  Hits  Doubles  Triples  HR  RBI  Walks   SO  \
0      3300  0.272  0.302    69   153       21        4  31  104     22   80   
1      2600  0.269  0.335    58   111       17        2  18   66     39   69   
2      2500  0.249  0.337    54   115       15        1  17   73     63  116   
3      2475  0.260  0.292    59   128       22        7  12   50     23   64   
4      2313  0.273  0.346    87   169       28        5   8   58     70   53   
5      2175  0.291  0.379   104   170       32        2  26  100     87   89   
6       600  0.258  0.370    34    86       14        1  14   38     15   45   
7       460  0.228  0.279    16    38        7        2   3   21     11   32   
8       240  0.250  0.327    40    61       11        0   1   18     24   26   
9       200  0.203  0.240    39    64       10        1  10   33     14   96   
10      177  0.262  0.283     7    38        5        0   0   10      5   18   
11      140  0.222  0.307    21    45        9        0   6   22     19   56   
12      117  0.227  0.280     4     5        2        0   1    3      2    1   
13      115  0.261  0.370     1     6        0        0   0    2      4    3   
14     2600  0.300  0.368    69   141       22        3  19   75     53   64   
15     1907  0.225  0.292    60   130       22        1  13   73     50  100   
16     1190  0.255  0.321    39   108       22        8   3   26     42   61   
17      990  0.290  0.349    59   141       30        2  16   64     42  102   
18      925  0.246  0.323    22    81       14        0   6   26     22   26   
19      365  0.208  0.265    12    35       11        1   0   15     14   30   
20      302  0.238  0.347    83   134       15        4  10   51     95  151   
21      300  0.267  0.310    73   149       23        9   6   39     34   89   
22      129  0.353  0.435    16    48       12        2   2   18     20   22   
23      111  0.213  0.222     4    13        4        1   1    8      1   18   
24     6100  0.302  0.391   102   174       44        6  18  100     90   67   
25     4125  0.260  0.321    69   150       23        1  19   96     55   74   
26     3213  0.255  0.347    45    71        7        5   1   17     39   47   
27     2319  0.259  0.349   108   146       34        4  38  117     78  120   
28     2000  0.223  0.307    43    84       10        4  10   40     36   56   
29     1600  0.225  0.310    44    96        9        3   0   31     50   69   
..      ...    ...    ...   ...   ...      ...      ...  ..  ...    ...  ...   
307     205  0.249  0.336    33    46        8        0   3   21     23   42   
308     185  0.238  0.289    21    56        5        1   0   21     14   37   
309     115  0.235  0.268     9    16        5        0   2    4      3   11   
310    3750  0.256  0.338    52    95       13        1  27   69     43   57   
311    2188  0.248  0.300    58   139       29        3  17   88     44   61   
312    2167  0.254  0.332    95   160       34        6   3   57     72   63   
313    2167  0.194  0.286    38    63        8        1   8   32     34   49   
314    2050  0.327  0.399    76   179       42        1  22  100     71   82   
315    1445  0.244  0.337    64    99       14        4  27   77     53  117   
316     875  0.305  0.347    35    54        6        2   6   23     10   27   
317     560  0.307  0.405    98   167       35        1  14   52     84   72   
318     360  0.230  0.302    42    98       16        4   1   41     45   37   
319     162  0.247  0.286    16    44       13        0   2   22      9   38   
320     133  0.205  0.272    11    23        2        0   4    9     11   24   
321     109  0.216  0.285    38    87       12        0  19   51     35  117   
322    4300  0.266  0.359   115   152       32        1  44  122     78  152   
323    3850  0.322  0.389   115   203       49        3  26   88     68   72   
324    2387  0.341  0.408   108   201       27        3  15   78     65   78   
325  

In [64]:
# You can perform queries on your data frame.  
# This statement gives you a True/False vector telling you 
# whether the player in each row has a salary over $1 Million
millionaire_indices = baseball['Salary'] > 1000
print millionaire_indices

0      True
1      True
2      True
3      True
4      True
5      True
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14     True
...
322     True
323     True
324     True
325    False
326    False
327    False
328    False
329    False
330    False
331    False
332    False
333    False
334    False
335    False
336    False
Name: Salary, Length: 337, dtype: bool


In [65]:
# you can use the query indices to look at a subset of your original dataframe
print 'baseball.shape:', baseball.shape
print "baseball[millionaire_indices].shape:", baseball[millionaire_indices].shape

baseball.shape: (337, 18)
baseball[millionaire_indices].shape: (139, 18)


In [66]:
# you can look at a subset of rows and columns at the same time
print "baseball[millionaire_indices][['Salary', 'AVG', 'Runs', 'Name']]:"
baseball[millionaire_indices][['Salary', 'AVG', 'Runs', 'Name']]

baseball[millionaire_indices][['Salary', 'AVG', 'Runs', 'Name']]:


Salary    AVG  Runs              Name
0      3300  0.272    69      Andre Dawson
1      2600  0.269    58     Steve Buchele
2      2500  0.249    54       Kal Daniels
3      2475  0.260    59    Shawon Dunston
4      2313  0.273    87        Mark Grace
5      2175  0.291   104     Ryne Sandberg
14     2600  0.300    69     Ivan Calderon
15     1907  0.225    60       Tim Wallach
16     1190  0.255    39        Spike Owen
24     6100  0.302   102     Bobby Bonilla
25     4125  0.260    69      Eddie Murray
26     3213  0.255    45     Vince Coleman
27     2319  0.259   108    Howard Johnson
28     2000  0.223    43        Kevin Bass
29     1600  0.225    44    Dick Schofield
30     1394  0.258    58      Dave Magadan
38     2567  0.196    36    Darren Daulton
39     2500  0.252    66       Dale Murphy
40     2350  0.294    84         John Kruk
41     2317  0.297    48     Lenny Dykstra
42     2000  0.258    46    Mariano Duncan
51     5150  0.292    95       Barry Bonds
52     4450  0.265    87    Andy Van Slyke
53     2000  0.265    53         Jose Lind
54     1850  0.289    25   Mike LaValliere
55     1192  0.295    19       Don Slaught
65     2425  0.272    41    Pedro Guerrero
66     2367  0.219    34  Andres Galarraga
67     2050  0.240    37      Jose Guillen
68     2000  0.285    96       Ozzie Smith
..      ...    ...   ...               ...
257    1350  0.241    42      Carlton Fisk
268    4200  0.301    79      Wally Joyner
269    3417  0.259    65  Kevin McReynolds
270    3100  0.255    77      George Brett
271    1650  0.301    47    Jim Eisenreich
272    1150  0.272    59    Gregg Jeffries
284    3100  0.284    72        Kent Hrbek
285    2992  0.319    92     Kirby Puckett
286    2800  0.277    84       Chili Davis
287    2500  0.311    54      Brian Harper
288    1933  0.265    52        Greg Gagne
289    1200  0.279    36   Mike Pagliarulo
290    1075  0.310    79        Shane Mack
296    5000  0.307   110      Ruben Sierra
297    3250  0.268   105  Rickey Henderson
298    2825  0.201    62      Mark McGwire
299    2600  0.276    86    Dave Henderson
300    2050  0.274    50   Terry Steinbach
301    1583  0.295    76     Harold Baines
302    1150  0.063     0   Carney Lansford
303    1100  0.238    38     Willie Wilson
310    3750  0.256    52    Kevin Mitchell
311    2188  0.248    58      Pete O'Brien
312    2167  0.254    95   Harold Reynolds
313    2167  0.194    38        Dave Valle
314    2050  0.327    76       Ken Griffey
315    1445  0.244    64        Jay Buhner
322    4300  0.266   115      Jose Canseco
323    3850  0.322   115   Rafael Palmeiro
324    2387  0.341   108      Julio Franco

[139 rows x 4 columns]

## Pandas Joins
The real magic with a Pandas DataFrame comes from the merge method which can match up the rows and columns from two DataFrames and combine their data.  Let's load another file which has shoesize for just a few players

In [67]:
# load shoe size data
shoe_size_df = pd.read_csv('data/baseball2.dat.txt')
shoe_size_df

Shoe Size          Name
0         11  Andre Dawson
1         13    Mark Grace
2         12    Sammy Sosa

In [70]:
merged = pd.merge(baseball, shoe_size_df, on=['Name'])
merged

Salary    AVG    OBP  Runs  Hits  Doubles  Triples  HR  RBI  Walks  SO  SB  \
0    3300  0.272  0.302    69   153       21        4  31  104     22  80   4   
1    2313  0.273  0.346    87   169       28        5   8   58     70  53   3   
2     200  0.203  0.240    39    64       10        1  10   33     14  96  13   

   Errs  free agency eligibility  free agent in 1991/2  \
0     3                        1                     0   
1     8                        0                     0   
2     6                        0                     0   

   arbitration eligibility  arbitration in 1991/2          Name  Shoe Size  
0                        0                      0  Andre Dawson         11  
1                        1                      0    Mark Grace         13  
2                        0                      0    Sammy Sosa         12

In [71]:
merged_outer = pd.merge(baseball, shoe_size_df, on=['Name'], how='outer')
merged_outer.head()

Salary    AVG    OBP  Runs  Hits  Doubles  Triples  HR  RBI  Walks   SO  \
0    3300  0.272  0.302    69   153       21        4  31  104     22   80   
1    2600  0.269  0.335    58   111       17        2  18   66     39   69   
2    2500  0.249  0.337    54   115       15        1  17   73     63  116   
3    2475  0.260  0.292    59   128       22        7  12   50     23   64   
4    2313  0.273  0.346    87   169       28        5   8   58     70   53   

   SB  Errs  free agency eligibility  free agent in 1991/2  \
0   4     3                        1                     0   
1   0     3                        1                     1   
2   6     5                        1                     0   
3  21    21                        0                     0   
4   3     8                        0                     0   

   arbitration eligibility  arbitration in 1991/2            Name  Shoe Size  
0                        0                      0    Andre Dawson         11  
1                        0                      0   Steve Buchele        NaN  
2                        0                      0     Kal Daniels        NaN  
3                        1                      0  Shawon Dunston        NaN  
4                        1                      0      Mark Grace         13

### <span style="color:red">Pandas Exercise: 7 Minutes</span>
1. Partner up with someone next to you.  Then, on one of your computers:
  1. Prepend a column of ones to the dataframe `X_df` below.  Name the new column 'const'.
  1. Again, matrix multiply `X_df` by the `betas` vector and assign the result to an new variable: `y_new`
  1. You'll know you've got it when the cell prints '\*\*\*\*\*\* Tests passed! \*\*\*\*\*\*' at the bottom.

  **Hint**: This stackoverflow post may be useful: http://stackoverflow.com/questions/13148429/how-to-change-the-order-of-dataframe-columns

In [ ]:
np.random.seed(3333)
n_data = 10 # number of data points. i.e. N
n_dim = 5   # number of dimensions of each datapoint.  i.e. D

betas = np.random.randn(n_dim + 1)

X_df = pd.DataFrame(data=np.random.randn(n_data, n_dim))

# INSERT YOUR CODE HERE!

# Tests:
assert 'const' in X_df.keys(), 'The new column must be called "const"'
assert np.all(X_df.shape == (n_data, n_dim+1))
assert len(y_new == n_data)
print '****** Tests passed! ******'